services:
  app:
    image: ${BACKEND_APP_IMAGE_NAME}
    build:
      context: ./back-end
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: build
    networks:
      - app-network

networks:
  app-network:
    driver: bridge