version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_REDIS_HOST: redis
      DB_PWD: ${DB_PWD}
      DB_USER_NAME: ${DB_USER_NAME}
      PAY_SECRET_KEY: ${PAY_SECRET_KEY}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      GOOGLE_ID: ${GOOGLE_ID}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
      KAKAO_ID: ${KAKAO_ID}
      KAKAO_SECRET: ${KAKAO_SECRET}
      NAVER_ID: ${NAVER_ID}
      NAVER_SECRET: ${NAVER_SECRET}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
      - redis

  db:
    image: oscarfonts/h2:latest
    port:
      - 1521:1521
      - 8081:81
    environment:
      H2_OPTIONS: -ifNotExists
    ports:
      - "3306:3306"
    volumes:
      - ./h2/:/opt/h2-data
    restart: always

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  h2:
  redis-data:
