version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      DB_PWD: ${DB_PWD}
      DB_USER_NAME: ${DB_USER_NAME}
      PAY_SECRET_KEY: ${PAY_SECRET_KEY}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      GOOGLE_ID: ${GOOGLE_ID}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
      KAKAO_ID: ${KAKAO_ID}
      KAKAO_SECRET: ${KAKAO_SECRET}
      NAVER_ID: ${NAVER_ID}
      NAVER_SECRET: ${NAVER_SECRET}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: oscarfonts/h2:latest
    ports:
      - "1521:1521"
      - "8082:8082"
    environment:
      H2_OPTIONS: -ifNotExists
    volumes:
      - ./h2/:/opt/h2-data
    restart: always
    networks:
      - app-net

  redis:
    image: redis:7
    hostname: redis
    command: redis-server
    ports:
      - "6379:6379"
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - app-net
    volumes:
      - redis-data:/data

networks:
  app-net:
    driver: bridge

volumes:
  redis-data:
