spring:
  application:
    name: usedAuction

  # 404 에러 핸들링을 위한 설정
  web:
    resources:
      add-mappings: false

  # 데이터베이스
  jpa:
    hibernate:
      ddl-auto: create
    database: h2
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 100

  datasource:
    username: ${DB_USER_NAME} # 환경 변수
    password: ${DB_PWD} # 환경 변수
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test

  h2:
    console:
      enabled: true
      path: /h2-console

  # redis
  data:
    redis:
      port: 6379
      host: localhost
  cache:
    type: redis

  #  # JWT 시크릿 키
  #  jwt:
  #    secret: ${JWT_SECRET} # 환경 변수

  # multipart
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

# S3
aws:
  s3:
    bucket: ${S3_BUCKET_NAME}
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
  region:
    static: ap-northeast-2
  stack:
    auto: false

# 로그
logging:
  level:
    org:
      hibernate:
        SQL: info
        type:
          descriptor:
            sql: trace
  config: classpath:logback-spring.xml

# 카카오페이 secretKey
payment:
  secret-key: ${PAY_SECRET_KEY}
  ready: https://open-api.kakaopay.com/online/v1/payment/ready