name: CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - back-end/**

jobs:
  build:
    name: Build Jar and Upload Docker Image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back-end

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew clean bootJar

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Image Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./back-end
          push: true
          tags: ${{ secrets.DOCKER_REPOSITORY_NAME }}:${{ github.sha }}
          platforms: linux/amd64

  deploy:
    name: Server Deployment
    needs: build
    runs-on: [ ubuntu-latest ]
    defaults:
      run:
        working-directory: back-end

    env:
      BACKEND_APP_IMAGE_NAME: ${{ secrets.DOCKER_REPOSITORY_NAME }}:${{ github.sha }}

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Compose up
        run: docker compose -f compose.yml up -d

      - name: Clean Unused Image
        run: docker image prune -af