name: CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Jar and Upload Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: |
          sudo chmod +x ./gradlew
          ./gradlew clean bootJar

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Image Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./
          push: true
          tags: ${{ secrets.DOCKER_REPOSITORY_NAME }}:v1
          platforms: linux/amd64

  deploy:
    name: Server Deployment
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Deploy to prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.PRIVATE_KEY }}

          script: |
            sudo docker compose -f /home/ubuntu/docker-compose.yml pull
            sudo docker compose -f /home/ubuntu/docker-compose.yml up -d
