name: CI

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [ 'main' ]

jobs:
  PATH_CHANGES:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      backend: ${{ steps.changes.outputs.backend }}

    steps:
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            backend:
              - 'back-end/**'

  BE_CI:
    runs-on: ubuntu-latest
    needs: PATH_CHANGES
    if: ${{ needs.PATH_CHANGES.outputs.backend == 'true' }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }} #뭔데

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Test with Gradle
        id: gradle_test
        run: |
          cd back-end
          ./gradlew test