name: CI

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [ 'main' ]

jobs:
  BE_CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Test with Gradle
        id: gradle_test
        run: |
          cd back-end
          ./gradlew test